### ISSUE TITLE
Handle SSL handshake timeouts with an error, instead of exception

### ISSUE THREAD

**Issue by scanner** [scanner/as_email_service#107]
```
smtpd   | [2023-11-23 00:33:21,869] ERROR:aiosmtpd.handle_exception: ('103.4.64.124', 60137) SMTP session exception
smtpd   | Traceback (most recent call last):
smtpd   |   File "/venv/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 914, in smtp_STARTTLS
smtpd   |     await waiter
smtpd   | ConnectionAbortedError: SSL handshake is taking longer than 60.0 seconds: aborting the connection
smtpd   | 
smtpd   | The above exception was the direct cause of the following exception:
smtpd   | 
smtpd   | Traceback (most recent call last):
smtpd   |   File "/venv/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 741, in _handle_client
smtpd   |     await method(arg)
smtpd   |   File "/venv/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 918, in smtp_STARTTLS
smtpd   |     raise TLSSetupException() from error
smtpd   | aiosmtpd.smtp.TLSSetupException
```

**Comment by scanner** [comment]
https://apricot-systematic.sentry.io/issues/4661742980/?alert_rule_id=14754796&alert_timestamp=1700728414624&alert_type=email&environment=production&notification_uuid=1adbe512-3413-4929-b050-0dc2278ed509&project=4506107525005312&referrer=alert_email
